import React from "react";
import {
    Copy,
    FullScreenExit,
    MicOff,
    Minus,
    MoreHorizontal,
    Plus,
    File,
    FileText,
    MunusSquire,
    Eye,
    AlertTrianle,
    EyeOff,
    Filter,
    Menu,
    AlertOctagon,
    AlertCircle,
    Bookmark,
    MinusCircle,
    PlusSquire,
    FullScreenEnter,
    Maximize,
    Bell,
    Move,
    Crop,
    BellOff,
    PlusCircle,
    PlayCircle,
    Check,
    RotageCW,
    CheckSquire,
    Play,
    Search,
    Repeat,
    DownloadCloude,
    Setting,
    Download,
    Globe,
    Login,
    QrCode,
    RotateCcw,
    Close,
    Refresh,
    ExternalLink,
    CheckCircle,
    Clipboard,
    Logout,
    HelpCircle,
    ShoppingCart,
    Save,
    Info,
    Home,
    Share,
    Heart,
    Trash,
    Export,
    Hash,
    Edit,
    ThumbsDown,
    ThumbsUp,
    Tag,
    Unlock,
    Traget,
    TrendingUp,
    TrendingDown,
    UploadCloud,
    Pause,
    Slider,
    Slash,
    Star,
    StopCircle,
    PauseCircle,
    Link,
    List,
    Zap,
    Shuffle,
    Lock,
    AlignJustify,
    AlertOnly,
    ZoomIn,
    ZoomOut,
    XCircle,
    XSquire,
    Upload,
    AlignRight,
    AlignLeft,
    AlignCenter,
    Anchor,
    Attachment,
    Bold,
    Delete,
    EditInline,
    EditCompose,
    FilePlus,
    FileMinus,
    Grid,
    Folder,
    Flag,
    Type,
    Minimize,
    Italic,
    Image,
    FileZip,
    Underline,
    Film,
    AirPlay,
    AtSign,
    Blutooth,
    Camera,
    CameraOff,
    Cast,
    Inbox,
    Mail,
    MessageCircle,
    MessageSquire,
    Mic,
    PhoneCall,
    Phone,
    PhoneOutgoing,
    PhoneOff,
    PhoneMissed,
    PhoneIncoming,
    PhoneForwarded,
    Send,
    MailOpen,
    Video,
    VideoOff,
    VoiceMail,
    Droplet,
    Disc,
    CrossShair,
    Circle,
    Chrome,
    Briefcase,
    Box,
    Book,
    WifiOff,
    Wifi,
    Layers,
    Layout,
    Sidebar,
    Squire,
    Triangle,
    LifeBoy,
    Loader,
    Octagon,
    Package,
    Percent,
    ArrowUpLeft,
    Wind,
    Ticket,
    Dot,
    MenuDots,
    Stamp,
    Bill,
    Coins,
    Appstore,
    Announcement,
    Sheild,
    ChevronUp,
    ArrowUpRight,
    ArrowLeft,
    ArrowUp,
    ArrowDownRight,
    ArrowDownLeft,
    ArrowDown,
    ArrowRight,
    ChevronsRight,
    ChevronsLeft,
    ChevronsDown,
    ChevronsUp,
    ChevronRight,
    ChevronLeft,
    ChevronDown,
    Cloud,
    Clock,
    Calendar,
    VolumeHigh,
    VolumeLow,
    VolumeMute,
    Volume,
    SkipForward,
    Skipback,
    Rewind,
    Headphone,
    FastFroward,
    CornerLeftDown,
    CornerUpLeft,
    CornerDownRight,
    CornerLeftUp,
    CornerRightDown,
    CornerRightUp,
    CornerDownLeft,
    CornerUpRight,
    Cpu,
    Battery,
    BetterCharging,
    Users,
    UserMinus,
    UserPlus,
    UserX,
    User,
    UserCheck,
    Cloudrain,
    Watch,
    Sun,
    Sunrise,
    Sunset,
    Moon,
    CloudLighting,
    CloudeOff,
    CloudeSnow,
    CloudDrizzle,
    History,
    Codepen,
    Tv,
    Thermometer,
    Tablet,
    Speaker,
    Smartphone,
    Server,
    Radio,
    Monitor,
    Printer,
    BarChartAlt,
    Activity,
    Twitter,
    Slack,
    Pocket,
    Instagram,
    Hithub,
    Gitlab,
    Resizer,
    Ruppes,
    Dollar,
    CreditCard,
    Navigation,
    MapPin,
    Compass,
    Map,
    BarChart,
    PaiChart,
    Facebook,
} from "./Icons";

export const IconsData = ({ ...rest }) => {
    const Icons = [
        {
            icon: <Copy {...rest} />,
            name: "Copy",
            data: ["copy"],
        },
        {
            icon: <Plus {...rest} />,
            name: "Plus",
            data: ["plus"],
        },
        {
            icon: <FullScreenExit {...rest} />,
            name: "FullScreenExit",
            data: ["full scree"],
        },
        {
            icon: <MicOff {...rest} />,
            name: "MicOff",
            data: ["mic off"],
        },
        {
            icon: <MoreHorizontal {...rest} />,
            name: "MoreHorizontal",
            data: ["More Horizontal"],
        },
        {
            icon: <Minus {...rest} />,
            name: "Minus",
            data: ["minus"],
        },
        {
            icon: <File {...rest} />,
            name: "File",
            data: ["file"],
        },
        {
            icon: <FileText {...rest} />,
            name: "FileText",
            data: ["plus"],
        },
        {
            icon: <MunusSquire {...rest} />,
            name: "MunusSquire",
            data: ["plus"],
        },
        {
            icon: <Eye {...rest} />,
            name: "Eye",
            data: ["plus"],
        },
        {
            icon: <AlertTrianle {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <EyeOff {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Filter {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Menu {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <AlertOctagon {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <AlertCircle {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Bookmark {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <MinusCircle {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <PlusSquire {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <FullScreenEnter {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Maximize {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Bell {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Move {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Crop {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <BellOff {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <PlusCircle {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <CheckSquire {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <RotageCW {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Check {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Play {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <PlayCircle {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Repeat {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <DownloadCloude {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Setting {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Download {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Globe {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Login {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Search {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <QrCode {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <RotateCcw {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Clipboard {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        }, {
            icon: <Close {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Refresh {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <ExternalLink {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <CheckCircle {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Edit {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Hash {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Export {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Trash {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Heart {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Share {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <CheckCircle {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <CheckCircle {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <CheckCircle {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Home {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Info {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Save {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <ShoppingCart {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <HelpCircle {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Logout {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Shuffle {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Zap {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <List {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Link {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <PauseCircle {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <StopCircle {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Star {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Lock {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Slash {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Slider {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Pause {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <UploadCloud {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <TrendingDown {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <TrendingUp {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <TrendingUp {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Traget {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Unlock {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Tag {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <ThumbsUp {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <ThumbsDown {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Upload {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <XSquire {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <XCircle {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <ZoomOut {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <ZoomIn {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <AlertOnly {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <AlignJustify {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <AlignRight {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <AlignLeft {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <AlignCenter {...rest} />,
            name: "AlertTrianle",
            data: ["plus"],
        },
        {
            icon: <Anchor {...rest} />,
            name: "Anchor",
            data: ["plus"],
        },
        {
            icon: <Attachment {...rest} />,
            name: "Attachment",
            data: ["plus"],
        },
        {
            icon: <Bold {...rest} />,
            name: "Bold",
            data: ["plus"],
        },
        {
            icon: <Delete {...rest} />,
            name: "Delete",
            data: ["plus"],
        },
        {
            icon: <EditInline {...rest} />,
            name: "EditInline",
            data: ["plus"],
        },
        {
            icon: <EditCompose {...rest} />,
            name: "EditCompose",
            data: ["plus"],
        },
        {
            icon: <FilePlus {...rest} />,
            name: "FilePlus",
            data: ["plus"],
        },
        {
            icon: <FileMinus {...rest} />,
            name: "FileMinus",
            data: ["plus"],
        },
        {
            icon: <Flag {...rest} />,
            name: "Flag",
            data: ["plus"],
        },
        {
            icon: <Folder {...rest} />,
            name: "Folder",
            data: ["plus"],
        },
        {
            icon: <Grid {...rest} />,
            name: "Grid",
            data: ["plus"],
        },
        {
            icon: <Image {...rest} />,
            name: "Image",
            data: ["plus"],
        },
        {
            icon: <Italic {...rest} />,
            name: "Italic",
            data: ["plus"],
        },
        {
            icon: <Minimize {...rest} />,
            name: "Minimize",
            data: ["plus"],
        },
        {
            icon: <Type {...rest} />,
            name: "Type",
            data: ["plus"],
        },
        {
            icon: <FileZip {...rest} />,
            name: "FileZip",
            data: ["plus"],
        },
        {
            icon: <Underline {...rest} />,
            name: "Underline",
            data: ["plus"],
        },
        {
            icon: <Film {...rest} />,
            name: "Film",
            data: ["plus"],
        },
        {
            icon: <AirPlay {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <AtSign {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <Blutooth {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <Camera {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <CameraOff {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <Cast {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <Inbox {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <Mail {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <MessageCircle {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <MessageSquire {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <Mic {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <PhoneCall {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <Phone {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <PhoneOutgoing {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <PhoneOff {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <PhoneMissed {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <PhoneIncoming {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <PhoneForwarded {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <Send {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <MailOpen {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <Video {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <VideoOff {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <VoiceMail {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <Wifi {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <WifiOff {...rest} />,
            name: "AirPlay",
            data: ["plus"],
        },
        {
            icon: <Book {...rest} />,
            name: "Book",
            data: ["plus"],
        },
        {
            icon: <Box {...rest} />,
            name: "Box",
            data: ["plus"],
        },
        {
            icon: <Briefcase {...rest} />,
            name: "Briefcase",
            data: ["plus"],
        },
        {
            icon: <Chrome {...rest} />,
            name: "Chrome",
            data: ["plus"],
        },
        {
            icon: <Circle {...rest} />,
            name: "Circle",
            data: ["plus"],
        },
        {
            icon: <CrossShair {...rest} />,
            name: "CrossShair",
            data: ["plus"],
        },
        {
            icon: <Disc {...rest} />,
            name: "Disc",
            data: ["plus"],
        },
        {
            icon: <Droplet {...rest} />,
            name: "Droplet",
            data: ["plus"],
        },
        {
            icon: <Layers {...rest} />,
            name: "Layers",
            data: ["plus"],
        },
        {
            icon: <Layout {...rest} />,
            name: "Layout",
            data: ["plus"],
        },
        {
            icon: <Sidebar {...rest} />,
            name: "Sidebar",
            data: ["plus"],
        },
        {
            icon: <Squire {...rest} />,
            name: "Squire",
            data: ["plus"],
        },
        {
            icon: <Triangle {...rest} />,
            name: "Triangle",
            data: ["plus"],
        },
        {
            icon: <LifeBoy {...rest} />,
            name: "LifeBoy",
            data: ["plus"],
        },
        {
            icon: <Loader {...rest} />,
            name: "Loader",
            data: ["plus"],
        },
        {
            icon: <Octagon {...rest} />,
            name: "Octagon",
            data: ["plus"],
        },
        {
            icon: <Package {...rest} />,
            name: "Package",
            data: ["plus"],
        },
        {
            icon: <Percent {...rest} />,
            name: "Percent",
            data: ["plus"],
        },
        {
            icon: <Sheild {...rest} />,
            name: "Sheild",
            data: ["plus"],
        },
        {
            icon: <Announcement {...rest} />,
            name: "Announcement",
            data: ["plus"],
        },
        {
            icon: <Appstore {...rest} />,
            name: "Appstore",
            data: ["plus"],
        },
        {
            icon: <Coins {...rest} />,
            name: "Coins",
            data: ["plus"],
        },
        {
            icon: <Bill {...rest} />,
            name: "Bill",
            data: ["plus"],
        },
        {
            icon: <Stamp {...rest} />,
            name: "Stamp",
            data: ["plus"],
        },
        {
            icon: <MenuDots {...rest} />,
            name: "MenuDots",
            data: ["plus"],
        },
        {
            icon: <Dot {...rest} />,
            name: "Dot",
            data: ["plus"],
        },
        {
            icon: <Ticket {...rest} />,
            name: "Ticket",
            data: ["plus"],
        },
        {
            icon: <Wind {...rest} />,
            name: "Wind",
            data: ["plus"],
        },
        {
            icon: <ArrowUpLeft {...rest} />,
            name: "ArrowUpLeft",
            data: ["plus"],
        },
        {
            icon: <ArrowUpRight {...rest} />,
            name: "ArrowUpRight",
            data: ["plus"],
        },
        {
            icon: <ArrowLeft {...rest} />,
            name: "ArrowLeft",
            data: ["plus"],
        },
        {
            icon: <ArrowUp {...rest} />,
            name: "ArrowUp",
            data: ["plus"],
        },
        {
            icon: <ArrowDownRight {...rest} />,
            name: "ArrowDownRight",
            data: ["plus"],
        },
        {
            icon: <ArrowDownLeft {...rest} />,
            name: "ArrowDownLeft",
            data: ["plus"],
        },
        {
            icon: <ArrowDown {...rest} />,
            name: "ArrowDown",
            data: ["plus"],
        },
        {
            icon: <ArrowRight {...rest} />,
            name: "ArrowRight",
            data: ["plus"],
        },
        {
            icon: <ChevronsRight {...rest} />,
            name: "ChevronsRight",
            data: ["plus"],
        },
        {
            icon: <ChevronsLeft {...rest} />,
            name: "ChevronsLeft",
            data: ["plus"],
        },
        {
            icon: <ChevronsDown {...rest} />,
            name: "ChevronsDown",
            data: ["plus"],
        },
        {
            icon: <ChevronsUp {...rest} />,
            name: "ChevronsUp",
            data: ["plus"],
        },
        {
            icon: <ChevronRight {...rest} />,
            name: "ChevronRight",
            data: ["plus"],
        },
        {
            icon: <ChevronLeft {...rest} />,
            name: "ChevronLeft",
            data: ["plus"],
        },
        {
            icon: <ChevronDown {...rest} />,
            name: "ChevronDown",
            data: ["plus"],
        },
        {
            icon: <ChevronUp {...rest} />,
            name: "ChevronUp",
            data: ["plus"],
        },
        {
            icon: <CornerUpRight {...rest} />,
            name: "CornerUpRight",
            data: ["plus"],
        },
        {
            icon: <CornerDownLeft {...rest} />,
            name: "CornerDownLeft",
            data: ["plus"],
        },
        {
            icon: <CornerRightUp {...rest} />,
            name: "CornerRightUp",
            data: ["plus"],
        },
        {
            icon: <CornerRightDown {...rest} />,
            name: "CornerRightDown",
            data: ["plus"],
        },
        {
            icon: <CornerLeftUp {...rest} />,
            name: "CornerLeftUp",
            data: ["plus"],
        },
        {
            icon: <CornerDownRight {...rest} />,
            name: "CornerDownRight",
            data: ["plus"],
        },
        {
            icon: <CornerUpLeft {...rest} />,
            name: "CornerUpLeft",
            data: ["plus"],
        },
        {
            icon: <CornerLeftDown {...rest} />,
            name: "CornerLeftDown",
            data: ["plus"],
        },
        {
            icon: <FastFroward {...rest} />,
            name: "FastFroward",
            data: ["plus"],
        },
        {
            icon: <Headphone {...rest} />,
            name: "Headphone",
            data: ["plus"],
        },
        {
            icon: <Rewind {...rest} />,
            name: "Rewind",
            data: ["plus"],
        },
        {
            icon: <Skipback {...rest} />,
            name: "Skipback",
            data: ["plus"],
        },
        {
            icon: <SkipForward {...rest} />,
            name: "SkipForward",
            data: ["plus"],
        },
        {
            icon: <Volume {...rest} />,
            name: "Volume",
            data: ["plus"],
        },
        {
            icon: <VolumeMute {...rest} />,
            name: "VolumeMute",
            data: ["plus"],
        },
        {
            icon: <VolumeLow {...rest} />,
            name: "VolumeLow",
            data: ["plus"],
        },
        {
            icon: <VolumeHigh {...rest} />,
            name: "VolumeHigh",
            data: ["plus"],
        },
        {
            icon: <Calendar {...rest} />,
            name: "Calendar",
            data: ["plus"],
        },
        {
            icon: <Clock {...rest} />,
            name: "Clock",
            data: ["plus"],
        },
        {
            icon: <Cloud {...rest} />,
            name: "Cloud",
            data: ["plus"],
        },
        {
            icon: <CloudDrizzle {...rest} />,
            name: "CloudDrizzle",
            data: ["plus"],
        },
        {
            icon: <CloudeSnow {...rest} />,
            name: "CloudeSnow",
            data: ["plus"],
        },
        {
            icon: <CloudeOff {...rest} />,
            name: "CloudeOff",
            data: ["plus"],
        },
        {
            icon: <CloudLighting {...rest} />,
            name: "CloudLighting",
            data: ["plus"],
        },
        {
            icon: <Moon {...rest} />,
            name: "Moon",
            data: ["plus"],
        },
        {
            icon: <Sunset {...rest} />,
            name: "Sunset",
            data: ["plus"],
        },
        {
            icon: <Sunrise {...rest} />,
            name: "Sunrise",
            data: ["plus"],
        },
        {
            icon: <Sun {...rest} />,
            name: "Sun",
            data: ["plus"],
        },
        {
            icon: <Watch {...rest} />,
            name: "Watch",
            data: ["plus"],
        },
        {
            icon: <Cloudrain {...rest} />,
            name: "Cloudrain",
            data: ["plus"],
        },
        {
            icon: <History {...rest} />,
            name: "History",
            data: ["plus"],
        },
        {
            icon: <UserCheck {...rest} />,
            name: "UserCheck",
            data: ["plus"],
        },
        {
            icon: <User {...rest} />,
            name: "User",
            data: ["plus"],
        },
        {
            icon: <UserX {...rest} />,
            name: "UserX",
            data: ["plus"],
        },
        {
            icon: <UserPlus {...rest} />,
            name: "UserPlus",
            data: ["plus"],
        },
        {
            icon: <UserMinus {...rest} />,
            name: "UserMinus",
            data: ["plus"],
        },
        {
            icon: <Users {...rest} />,
            name: "Users",
            data: ["plus"],
        },
        {
            icon: <BetterCharging {...rest} />,
            name: "BetterCharging",
            data: ["plus"],
        },
        {
            icon: <Battery {...rest} />,
            name: "Battery",
            data: ["plus"],
        },
        {
            icon: <Cpu {...rest} />,
            name: "Cpu",
            data: ["plus"],
        },
        {
            icon: <Monitor {...rest} />,
            name: "Monitor",
            data: ["plus"],
        },
        {
            icon: <Printer {...rest} />,
            name: "Printer",
            data: ["plus"],
        },
        {
            icon: <Radio {...rest} />,
            name: "Radio",
            data: ["plus"],
        },
        {
            icon: <Server {...rest} />,
            name: "Server",
            data: ["plus"],
        },
        {
            icon: <Smartphone {...rest} />,
            name: "Smartphone",
            data: ["plus"],
        },
        {
            icon: <Speaker {...rest} />,
            name: "Speaker",
            data: ["plus"],
        },
        {
            icon: <Tablet {...rest} />,
            name: "Tablet",
            data: ["plus"],
        },
        {
            icon: <Thermometer {...rest} />,
            name: "Thermometer",
            data: ["plus"],
        },
        {
            icon: <Tv {...rest} />,
            name: "Tv",
            data: ["plus"],
        },
        {
            icon: <Codepen {...rest} />,
            name: "Codepen",
            data: ["plus"],
        },
        {
            icon: <Facebook {...rest} />,
            name: "Facebook",
            data: ["plus"],
        },
        {
            icon: <Gitlab {...rest} />,
            name: "Gitlab",
            data: ["plus"],
        },
        {
            icon: <Hithub {...rest} />,
            name: "Hithub",
            data: ["plus"],
        },
        {
            icon: <Instagram {...rest} />,
            name: "Instagram",
            data: ["plus"],
        },
        {
            icon: <Pocket {...rest} />,
            name: "Pocket",
            data: ["plus"],
        },
        {
            icon: <Slack {...rest} />,
            name: "Slack",
            data: ["plus"],
        },
        {
            icon: <Twitter {...rest} />,
            name: "Twitter",
            data: ["plus"],
        },
        {
            icon: <Activity {...rest} />,
            name: "Activity",
            data: ["plus"],
        },
        {
            icon: <BarChartAlt {...rest} />,
            name: "BarChartAlt",
            data: ["plus"],
        },
        {
            icon: <BarChart {...rest} />,
            name: "BarChart",
            data: ["plus"],
        },
        {
            icon: <PaiChart {...rest} />,
            name: "PaiChart",
            data: ["plus"],
        },
        {
            icon: <Compass {...rest} />,
            name: "Compass",
            data: ["plus"],
        },
        {
            icon: <Map {...rest} />,
            name: "Map",
            data: ["plus"],
        },
        {
            icon: <MapPin {...rest} />,
            name: "MapPin",
            data: ["plus"],
        },
        {
            icon: <Navigation {...rest} />,
            name: "Navigation",
            data: ["plus"],
        },
        {
            icon: <CreditCard {...rest} />,
            name: "CreditCard",
            data: ["plus"],
        },
        {
            icon: <Dollar {...rest} />,
            name: "Dollar",
            data: ["plus"],
        },
        {
            icon: <Ruppes {...rest} />,
            name: "Ruppes",
            data: ["plus"],
        },
        {
            icon: <Resizer {...rest} />,
            name: "Resizer",
            data: ["plus"],
        },

    ]
    return Icons;
}




// command